site_name: ChameleonForms
theme: readthedocs
markdown_extensions: [fenced_code]
pages:
- Home: index.md
- Philosophy:
  - Why is ChameleonForms needed: why.md
- Basic usage:
  - Getting started: getting-started.md
  - Configuring ChameleonForms: configuration.md
  - Comparison: comparison.md
  - Bootstrap Template: bootstrap-template.md
  - Control field labels: labels.md
  - Field Configuration: field-configuration.md
  - HTML Attributes: html-attributes.md
  - Change the model type for HTML Helper for portions of your page: html-helper-context.md
  - Create a form against a model type different from the page model: different-form-models.md
  - Use partial views for repeated or abstracted form areas: partials.md
- Form structure:
  - Form: the-form.md
  - Message: the-message.md
  - Section: the-section.md
  - Navigation: the-navigation.md
  - Field: field.md
  - Field Element: field-element.md
  - Field Label: field-label.md
  - Field Validation HTML: field-validation-html.md
- Field types:
  - Boolean fields: boolean.md
  - DateTime fields: datetime.md
  - Client-side validation of DateTime fields: datetime-client-side-validation.md
  - Enum fields: enum.md
  - Flags enum fields: flags-enum.md
  - Multiple-select enum fields: multiple-enum.md
  - List fields: list.md
  - Multiple-select list fields: multiple-list.md
  - Textarea fields: textarea.md
  - File upload fields: file-upload.md
  - Password fields: password.md
  - Number fields: number.md
  - Email fields: email.md
  - URI fields: uri.md
  - Default fields: default-fields.md
- Advanced usage:
  - Using different form templates: form-templates.md
  - Creating custom form templates: custom-template.md
  - Extending the field configuration: extending-field-configuration.md
  - Extending the form components: extending-form-components.md
  - Creating and using a custom field generator: custom-field-generator.md
  - Creating and using custom field generator handlers: custom-field-generator-handlers.md
